/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShareRouteImport } from './routes/_app/share'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events.$eventId'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people.index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people.$personId'
import { Route as EventsEventIdPrintRouteImport } from './routes/events.$eventId.print'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShareRoute = AppShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)
const EventsEventIdPrintRoute = EventsEventIdPrintRouteImport.update({
  id: '/events/$eventId/print',
  path: '/events/$eventId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/share': typeof AppShareRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/share': typeof AppShareRoute
  '/': typeof AppIndexRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/share': typeof AppShareRoute
  '/_app/': typeof AppIndexRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/join'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/settings'
    | '/share'
    | '/events/$eventId'
    | '/people/$personId'
    | '/events/$eventId/print'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/join'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/settings'
    | '/share'
    | '/'
    | '/events/$eventId'
    | '/people/$personId'
    | '/events/$eventId/print'
    | '/people'
  id:
    | '__root__'
    | '/_app'
    | '/contact'
    | '/join'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/_app/settings'
    | '/_app/share'
    | '/_app/'
    | '/_app/events/$eventId'
    | '/_app/people/$personId'
    | '/events/$eventId/print'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  EventsEventIdPrintRoute: typeof EventsEventIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/share': {
      id: '/_app/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AppShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/events/$eventId/print': {
      id: '/events/$eventId/print'
      path: '/events/$eventId/print'
      fullPath: '/events/$eventId/print'
      preLoaderRoute: typeof EventsEventIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppShareRoute: typeof AppShareRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppShareRoute: AppShareRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  EventsEventIdPrintRoute: EventsEventIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
